name: ubuntu-kokkos-serial
  
# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master

  pull_request:

  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: release
    steps:
      - name: install dependencies
        shell: bash
        run: |
             sudo apt-get update -y -qq
             sudo apt-get install -y libblas-dev liblapack-dev
             sudo apt-get install -y libmetis-dev
             sudo apt-get install -y netcdf-bin libnetcdf-dev
             sudo apt-get install -y libhdf5-serial-dev libhdf5-mpich-dev
             sudo add-apt-repository ppa:nschloe/seacas-nightly
             sudo apt-get update -y -qq
             sudo apt-get install -y seacas-bin libseacas-dev
             git clone https://github.com/kokkos/kokkos.git
             cd kokkos
             mkdir build && mkdir install && cd build
             cmake .. -DCMAKE_INSTALL_PREFIX="/usr/"
             make && sudo make install
  build-nimble-kokkos:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cmake
        shell: bash
        run: |
           echo $ACCESS
           export ACCESS=`pwd`
           echo $ACCESS
           ls >& TTTT && cat TTTT
           mkdir build && cd build
           ls >& TTTT && cat TTTT
           export DIR2=`pwd`
           echo $DIR2
           cmake -DCMAKE_CXX_FLAGS="-Werror" \
                 -Dexodus_INCLUDE_DIR="/usr/include" \
                 -Dexodus_LIBRARY="/usr/lib/x86_64-linux-gnu/libexodus.so" \
                 -DHAVE_KOKKOS=ON \
                 ..
      - name: compile
        run: cmake --build build
      - name: test
        run: |
           cd build
           export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${PATH}"
           make test

